### PR TITLE
Don't use the cache if the request has a Range header

### LINKED ISSUE #327: download of partial content is defeated by cachecontrol
suppose some large file is in the cache already and we make a request for partial content with a `Range` header.

understanding that caching of such things is likely to go wrong we also include the header `Cache-Control: no-cache`.

this header succeeds in preventing cachecontrol from responding immediately from the cache - but does not stop it from going through https://github.com/psf/cachecontrol/blob/7e3edbf61fa8d6cd2db1a0eed3a2e1c2fbc67d18/cachecontrol/adapter.py#L74 in which it unconditionally looks in the cache https://github.com/psf/cachecontrol/blob/7e3edbf61fa8d6cd2db1a0eed3a2e1c2fbc67d18/cachecontrol/controller.py#L273.  The result is that cachecontrol adds an `If-Modified-Since` header to the request, with timestamp per what is in the cache.

but now the server sees the header on that request, knows that the file has not been modified recently, and returns 304.  And now cachecontrol returns the entire file from its cache anyway, and not the partial content that the server would have given.

related-ish: #246 asks for cachecontrol to cache partial content.  But this one reports that cachecontrol makes partial content not work

### PR DESCRIPTION
**Pull request by dimbleby**
fixes #327

### CODE REVIEW

**Review by woodruffw — APPROVED** [review]
Thanks @dimbleby, LGTM. I'll let @frostming review as well before merging.

(Also, thanks for adding a test!)

**Comment by frostming** [comment]
Looks good for now. I think we would have to encode headers as well as the URL as the cache key.

**Comment by woodruffw** [comment]
> I think we would have to encode headers as well as the URL as the cache key.

Makes sense!

@dimbleby: Do you need a point release for this fix? If so, I can prep one tonight.

**Comment by frostming** [comment]
> @dimbleby: Do you need a point release for this fix? If so, I can prep one tonight.

I think so, we can cut a `0.14.0` release

**Comment by dimbleby** [comment]
thanks folks!

**Pull request merged**
